services:
  whoami-dashbord-demo:
    image: 'traefik/whoami'
    restart: unless-stopped

  mongodb:
    image: mongo:4.2.1-bionic
    restart: unless-stopped
    volumes:
      - dbdata:/data/db

  docker-api:
    build: backend/docker-api
    restart: unless-stopped
    ports:
      - 8080

  helloworld:
    build: backend/helloworld
    restart: unless-stopped
    ports:
      - 8080

  frontend:
    image: 192.168.10.61:5000/dashboard-demo-frontend
    restart: unless-stopped
    command: npm run start

  # bakend
  node-app:
    image: 192.168.10.61:5000/dashboard-demo-backend-node-app
    restart: unless-stopped
    command: npm run start
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/node-boilerplate
      # https://stackoverflow.com/questions/67903114/javascript-heap-out-of-memory-in-docker-image-run
      - NODE_OPTIONS=--max_old_space_size=2048
    depends_on:
      - mongodb

  documentation:
    image: 192.168.10.61:5000/dashboard-demo-documentation
    restart: unless-stopped
    command: npm run serve

volumes:
  dbdata:
  documentation_node_modules:
  frontend_node_modules:
