# NOTE: ./frontend contains source for frontend

services:
  frontend:
    build: ./frontend/app
    ports:
      - 3001:3000
    env_file: ./frontend/app/.env.development
    command: ./dev.sh
    volumes:
      - frontend_node_modules:/app/node_modules
      - ./frontend/app:/app

  email-server:
    image: mailhog/mailhog:latest
    ports:
      - 1025:1025
      - 8025:8025

  node-app:
    container_name: node-app-dev
    command: yarn dev -L
    # command: sleep infinity
    volumes:
      - ./backend/node-app:/usr/src/node-app:ro
    depends_on:
      - mongodb
      - email-server
    ports:
      # NOTE: for test locally using browser
      - 3000:3000

  mongodb:
    ports:
      # NOTE: explicity port mapping for db seeding
      - 27017:27017

  mongo-express:
    image: mongo-express:latest
    ports:
      - 8081:8081
    volumes:
      - ./volumes/backend/mongo-express:/app
      - ./volumes/backend/mongo-express/docker-entrypoint.sh:/docker-entrypoint.sh
    depends_on:
      - mongodb

    environment:
      # for wait in docker-entrypoint.sh
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      # - ME_CONFIG_BASICAUTH_USERNAME=user
      # - ME_CONFIG_BASICAUTH_PASSWORD=password

volumes:
  dbdata:
  documentation_node_modules:
  frontend_node_modules:
