FROM node:18-buster

# Set DEBIAN_FRONTEND to noninteractive
ENV DEBIAN_FRONTEND noninteractive

RUN mkdir -p /app
COPY . /app
RUN chown 1000:1000 -R /app
USER 1000:1000

WORKDIR /app

RUN npm install
RUN npm run build

# NOTE: default to production run
CMD ["npm", "run", "serve"]
